kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
# set your lab user name
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
# set your lab user name
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: {{ .Chart.Name }}-html
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html # this will mount the html.index file to it application location
          resources: {}
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10